upstream streamlit_pool {
    ip_hash;

    server streamlit1:8501;
    server streamlit2:8501;
    server streamlit3:8501;
}

server {
    listen 80;
    server_name riskcalc.duckdns.org;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# server {
#     listen 443 ssl;
#     server_name riskcalc.duckdns.org;

#     ssl_certificate /etc/letsencrypt/live/riskcalc.duckdns.org/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/riskcalc.duckdns.org/privkey.pem;

#     ssl_protocols TLSv1.2 TLSv1.3;
#     ssl_ciphers HIGH:!aNULL:!MD5;
#     ssl_prefer_server_ciphers on;

#     location / {
#         proxy_pass http://streamlit_pool;

#         proxy_http_version 1.1;
#         proxy_set_header Upgrade $http_upgrade;
#         proxy_set_header Connection "upgrade";

#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;

#         proxy_read_timeout 86400;
#         proxy_send_timeout 86400;
#     }

#     location /_stcore/health {
#         proxy_pass http://streamlit_pool;
#         proxy_http_version 1.1;
#         proxy_set_header Host $host;
#     }
# }
